// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCa3g6kF6BCr98gofTas6GcYYS4qG_OMwY',
    appId: '1:388002721586:web:707c3c1f413c6aa608712b',
    messagingSenderId: '388002721586',
    projectId: 'responsive-ca9f8',
    authDomain: 'responsive-ca9f8.firebaseapp.com',
    storageBucket: 'responsive-ca9f8.appspot.com',
    measurementId: 'G-XH0V5FG7E3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUSER1Zx4v6oD7IM1M4aE5XsxhoX85oLQ',
    appId: '1:388002721586:android:c107b3e24c8b552808712b',
    messagingSenderId: '388002721586',
    projectId: 'responsive-ca9f8',
    storageBucket: 'responsive-ca9f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAX_ZOS6Ebu8FQ3O4-LGMsthMpUwTSvUQI',
    appId: '1:388002721586:ios:1d5f10e7b0f2a9ae08712b',
    messagingSenderId: '388002721586',
    projectId: 'responsive-ca9f8',
    storageBucket: 'responsive-ca9f8.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAX_ZOS6Ebu8FQ3O4-LGMsthMpUwTSvUQI',
    appId: '1:388002721586:ios:1d5f10e7b0f2a9ae08712b',
    messagingSenderId: '388002721586',
    projectId: 'responsive-ca9f8',
    storageBucket: 'responsive-ca9f8.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCa3g6kF6BCr98gofTas6GcYYS4qG_OMwY',
    appId: '1:388002721586:web:e209f30b7fd94f4408712b',
    messagingSenderId: '388002721586',
    projectId: 'responsive-ca9f8',
    authDomain: 'responsive-ca9f8.firebaseapp.com',
    storageBucket: 'responsive-ca9f8.appspot.com',
    measurementId: 'G-X755QFG2YE',
  );
}
